spring:
  application:
    name: PatientManagement

  datasource:
    url: jdbc:mysql://localhost:3306/patientdb
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # options: validate | update | create | create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Use the appropriate dialect for your MySQL version

server:
  port: 8085 # Set your application's running port if different
